<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Sally Jung" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/jung_project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>#0. Dataset
setwd(&quot;/Users/SJ/Desktop&quot;)
iof &lt;- read.csv(&quot;LTREB2_GrassIOF_DataV2.csv&quot;)
iof &lt;- iof %&gt;% mutate(D_Area = pi*(D_X/2)*(D_Y/2)) %&gt;% mutate(G_Area = pi*(G_X/2)*(G_Y/2)) %&gt;% select(Treatment, D_Area, D_Height, G_Area, G_Height) %&gt;% mutate(y=ifelse(iof$Treatment==3,F,T)) %&gt;% mutate(Treatment= recode(Treatment,&quot;T1&quot;,&quot;T2&quot;,&quot;T3&quot;,&quot;T4&quot;,&quot;T5&quot;))
head(iof)</code></pre>
<pre><code>##   Treatment    D_Area D_Height    G_Area G_Height    y
## 1        T1   0.00000      0.0  11.62389      6.8 TRUE
## 2        T1 686.43799      5.0 368.03758      8.0 TRUE
## 3        T1 105.65176      4.6  48.38053      1.4 TRUE
## 4        T1   0.00000      0.0  12.01659      3.0 TRUE
## 5        T1 129.11946      1.5  27.48894     16.0 TRUE
## 6        T1  46.93539      1.6  14.29425      2.5 TRUE</code></pre>
<p>Introduction:</p>
<p>The dataset I chose is a subset of the dataset I used for Project 1. The variables I will be using in this project are Dune area (cm^2) and height (cm), Grass area (cm^2) and height (cm), Treatment (groups 1-5), and a binary variable where Control group = False and the Treatment groups = True. There are 487 observations in this dataset.</p>
<p>The data was collected by myself last summer when I was a REU intern. The lab I was with had rainfall manipulation experiments set up at the Jornada Long Term Ecological Research site in New Mexico to observe how changing rainfall would impact vegetation. Plots in the rainfall manipulation experiments consisted of plastic shingle roofs that blocked out a percentage of rain to simulate reduced rainfall, and the blocked water was collected and diverted to another plot through a sprinkler system to simulate increased rainfall. In the data, Treatment 1 represents reduced rainfall by 80% (-80%), Treatment 2 represents -50%, Treatment 3 represents the Control, Treatment 4 represents increased rainfall by 50% (+50%), and Treatment 5 represents +80%.</p>
<pre class="r"><code>#1. MANOVA
man1&lt;-manova(cbind(D_Area, D_Height, G_Area, G_Height)~Treatment, data=iof)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Treatment 4 0.11755 3.6484 16 1928 1.264e-06 ***
## Residuals 482
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response D_Area :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment 4 56392198 14098050 6.1135 8.353e-05 ***
## Residuals 482 1111514899 2306048
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response D_Height :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment 4 114.86 28.7145 6.5281 4.024e-05 ***
## Residuals 482 2120.13 4.3986
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response G_Area :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment 4 41272349 10318087 6.0191 9.862e-05 ***
## Residuals 482 826257173 1714226
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response G_Height :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment 4 900.5 225.116 8.6479 9.545e-07 ***
## Residuals 482 12547.1 26.031
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(iof$D_Area,iof$Treatment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  iof$D_Area and iof$Treatment 
## 
##    T1      T2      T3      T4     
## T2 0.05954 -       -       -      
## T3 0.00379 0.32249 -       -      
## T4 3.5e-05 0.02477 0.20357 -      
## T5 0.00014 0.05368 0.33558 0.76747
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(iof$D_Height,iof$Treatment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  iof$D_Height and iof$Treatment 
## 
##    T1      T2     T3     T4    
## T2 0.0093  -      -      -     
## T3 0.0109  0.9992 -      -     
## T4 1.7e-06 0.0259 0.0284 -     
## T5 0.0011  0.4316 0.4387 0.1703
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(iof$G_Area,iof$Treatment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  iof$G_Area and iof$Treatment 
## 
##    T1      T2      T3      T4     
## T2 0.04825 -       -       -      
## T3 0.00294 0.32688 -       -      
## T4 2.8e-05 0.02711 0.21302 -      
## T5 0.00025 0.08681 0.44893 0.63829
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(iof$G_Height,iof$Treatment,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  iof$G_Height and iof$Treatment 
## 
##    T1      T2      T3      T4     
## T2 0.98902 -       -       -      
## T3 0.01581 0.02501 -       -      
## T4 0.00030 0.00071 0.22516 -      
## T5 2.9e-06 1.2e-05 0.02652 0.32549
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>0.05/45</code></pre>
<pre><code>## [1] 0.001111111</code></pre>
<pre class="r"><code>1-(0.95^45)</code></pre>
<pre><code>## [1] 0.9005597</code></pre>
<pre class="r"><code>#multivariate normality
ggplot(iof, aes(x = D_Area, y = D_Height)) +
geom_point(alpha = .5) + geom_density_2d(h=2) + facet_wrap(~Treatment)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#homogeneity of covariance
covmats&lt;-iof%&gt;%group_by(Treatment)%&gt;%do(covs=cov(.[2:3]))
for(i in 1:3){print(as.character(covmats$Treatment[i])); print(covmats$covs[i])}</code></pre>
<pre><code>## [1] &quot;T1&quot;
## [[1]]
##               D_Area   D_Height
## D_Area   525468.9896 581.076638
## D_Height    581.0766   4.031872
## 
## [1] &quot;T2&quot;
## [[1]]
##               D_Area    D_Height
## D_Area   1842148.799 1091.001647
## D_Height    1091.002    4.507625
## 
## [1] &quot;T3&quot;
## [[1]]
##               D_Area    D_Height
## D_Area   3234075.785 1974.491845
## D_Height    1974.492    4.025039</code></pre>
<p>The MANOVA test was significant, meaning at least one of the dependent variables (Dune Area, Dune Height, Grass Area, Grass Height) their means differ by Treatment. The ANOVA test was significant, meaning that for all the dependent variables (DV), at least one Treatment differs.</p>
<p>Based on 45 tests (1 MANOVA, 4 ANOVA, 40 t-tests), the bonferroni correction is a = 0.0011. For Dune Area, Grass Area, and Dune Height, the mean of Treatment 1 is significantly different from Treatment 4 and 5. For Grass Height, the mean of Treatment 1 is significantly different from Treatment 4 and 5, and the mean of Treatment 2 is significantly different from Treatment 4 and 5.</p>
<p>Based on the graphs for multilinearity and matrices for homogeneity, it is most likely that assumptions have not been met. The type I error rate was 90%.</p>
<pre class="r"><code>#2. Randomization Test (PERMANOVA)
library(vegan)
dists&lt;-iof%&gt;%select(D_Area, D_Height, G_Area, G_Height)%&gt;%dist()
adonis(dists~Treatment,data=iof)</code></pre>
<pre><code>##
## Call:
## adonis(formula = dists ~ Treatment, data = iof)
##
## Permutation: free
## Number of permutations: 999
##
## Terms added sequentially (first to last)
##
## Df SumsOfSqs MeanSqs F.Model R2 Pr(&gt;F)
## Treatment 4 97665563 24416391 6.0733 0.04798 0.002 **
## Residuals 482 1937786738 4020304 0.95202
## Total 486 2035452301 1.00000
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>iof %&gt;% group_by(Treatment) %&gt;% summarize(n()) %&gt;% pull</code></pre>
<pre><code>## [1] 135  99  92  81  80</code></pre>
<pre class="r"><code>#compute observed F
SST&lt;- sum(dists^2)/487
SSW&lt;-iof%&gt;%group_by(Treatment)%&gt;%select(D_Area,D_Height,G_Area,G_Height)%&gt;%
do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
summarize(sum(d[[1]]^2)/135 + sum(d[[2]]^2)/99+ sum(d[[3]]^2)/92 + sum(d[[4]]^2)/81 + sum(d[[5]]^2)/80)%&gt;%pull
F_obs&lt;-((SST-SSW)/4)/(SSW/482) #observed F statistic
# compute null distribution for F
Fs&lt;-replicate(1000,{
new&lt;-iof%&gt;%mutate(Treatment=sample(Treatment)) #permute the species vector
SSW&lt;-new%&gt;%group_by(Treatment)%&gt;%select(D_Area,D_Height,G_Area,G_Height)%&gt;%
do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
summarize(sum(d[[1]]^2)/135 + sum(d[[2]]^2)/99+ sum(d[[3]]^2)/92 +
sum(d[[4]]^2)/81 + sum(d[[5]]^2)/80)%&gt;%pull
((SST-SSW)/4)/(SSW/482) #calculate new F on randomized data
})
quantile(Fs,.95)</code></pre>
<pre><code>##      95% 
## 93.42311</code></pre>
<pre class="r"><code>hist(Fs,prob = T); abline(v=F_obs, col=&quot;red&quot;, add=T)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>The null hypothesis is that mean sizes of Dune Area, Dune Height, Grass Area, and Grass Height are the same for each Treatment. The alternative hypothesis is that for at least one dependent variable, the mean sizes differ by Treatment. PERMANOVA was significant (p=0.001).</p>
<pre class="r"><code>#3. Linear Regression 
library(sandwich)
library(lmtest)

iof$D_Height_c &lt;- iof$D_Height - mean(iof$D_Height)
iof$G_Area_c &lt;- iof$G_Area - mean(iof$G_Area)

fit&lt;-lm(D_Area ~ D_Height_c*G_Area_c, data=iof)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = D_Area ~ D_Height_c * G_Area_c, data = iof)
##
## Residuals:
## Min 1Q Median 3Q Max
## -864.34 -83.81 -21.12 29.68 1991.30
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 907.764540 10.609418 85.562 &lt; 2e-16 ***
## D_Height_c 34.982273 4.949420 7.068 5.53e-12 ***
## G_Area_c 1.161221 0.010501 110.582 &lt; 2e-16 ***
## D_Height_c:G_Area_c -0.020540 0.003804 -5.400 1.05e-07
***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 214.9 on 483 degrees of freedom
## Multiple R-squared: 0.9809, Adjusted R-squared: 0.9808
## F-statistic: 8267 on 3 and 483 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>resids&lt;-fit$residuals; fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>bptest(fit) #testing heteroskedasticity assumption: Ho: homoskedsastic</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 42.361, df = 3, p-value = 3.364e-09</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids),bins=20)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))+geom_qq_line(aes(sample=resids), color=&#39;red&#39;)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, sd=sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.21394, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>#robust standard errors
coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                         Estimate   Std. Error
## (Intercept)         907.76453957 14.492031865
## D_Height_c           34.98227254  6.893015360
## G_Area_c              1.16122068  0.024780741
## D_Height_c:G_Area_c  -0.02054046  0.009370513</code></pre>
<pre class="r"><code>14.49-10.61</code></pre>
<pre><code>## [1] 3.88</code></pre>
<pre class="r"><code>6.89-4.95</code></pre>
<pre><code>## [1] 1.94</code></pre>
<pre class="r"><code>#Plot regression
fit&lt;-lm(D_Area ~ D_Height_c*G_Area_c, data=iof)
new1&lt;-iof
new1$D_Height_c&lt;-mean(iof$D_Height_c)
new1$mean&lt;-predict(fit,new1)
new1$D_Height_c&lt;-mean(iof$D_Height_c)+sd(iof$D_Height_c)
new1$plus.sd&lt;-predict(fit,new1)
new1$D_Height_c&lt;-mean(iof$D_Height_c)-sd(iof$D_Height_c)
new1$minus.sd&lt;-predict(fit,new1)
newint&lt;-new1%&gt;%select(D_Area,G_Area_c,mean,plus.sd,minus.sd)%&gt;%gather(D_Height,value,-D_Area,-G_Area_c)

mycols&lt;-c(&quot;#619CFF&quot;,&quot;#F8766D&quot;,&quot;#00BA38&quot;)
names(mycols)&lt;-c(&quot;-1 sd&quot;,&quot;mean&quot;,&quot;+1 sd&quot;)
mycols=as.factor(mycols)

ggplot(iof,aes(G_Area_c,D_Area),group=mycols)+geom_point()+geom_line(data=new1,aes(y=mean,color=&quot;mean&quot;))+geom_line(data=new1,aes(y=plus.sd,color=&quot;+1 sd&quot;))+geom_line(data=new1,aes(y=minus.sd,color=&quot;-1 sd&quot;))+scale_color_manual(values=mycols)+labs(color=&quot;Age (cont)&quot;)+theme(legend.position=c(.9,.2))</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<p>Assumptions of linearity, normality, and homoskedacity are not met.</p>
<p>Intercept means that the Dune Area is 907.76 cm^2 when when Dune Height and Grass Area is equal to their means. Holding Grass Area constant, the slope of Dune Height is 34.98 (one cm increase in Dune Height increases Dune Area by 34.98) Holding Dune Height constant, the slope of Grass Area is 1.16 (one cm^2 increase in Grass Area increases Dune Area by 1.16). For the interaction, as Dune Height increases, there is a weak linear relationship between Dune Area and Grass Area. For every cm increase in Dune Height, the slope for Grass Area goes down by 0.021.</p>
<p>All variables are significant. Controlling for Grass Area, Dune Height has an effect on Dune Area. Controlling for Dune Height, Grass Area has an effect on Dune Area. 98% of the variation in the outcome is explained by my model. The effect of Dune Height on Dune Area depends on Grass Area. There is not much difference before and after robust SE. After robust SE, SE increased by 3.9 for the Intercept and SE increased by 1.9 for Dune Height.</p>
<pre class="r"><code>#4. Bootstrap
fit1&lt;-lm(D_Area ~ D_Height_c*G_Area_c, data=iof)

#sample people/rows with replacement
boot_dat&lt;-iof[sample(nrow(iof),replace=TRUE),]
samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-boot_dat&lt;-iof[sample(nrow(iof),replace=TRUE),]
  fit1&lt;-lm(D_Area ~ D_Height_c*G_Area_c, data=boot_dat)
  coef(fit1)
})
## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) D_Height_c   G_Area_c D_Height_c:G_Area_c
## 1    14.16177    6.67975 0.02327641         0.009019529</code></pre>
<p>After bootstrapping, the SE values for all the variables (Intercept, Dune Height, Grass Area, Interaction) decreased. Because SE decreased, p-value would decrease as well, which would increase the chances of the variable turning significant.</p>
<pre class="r"><code>#5. Logistic Regression 
#Control = False (0), Treatment = True (1)
lfit&lt;-glm(y~D_Area+G_Height,data=iof, family=&#39;binomial&#39;)
coeftest(lfit)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 1.5914e+00 2.4685e-01 6.4470 1.141e-10 ***
## D_Area -4.4721e-05 7.8514e-05 -0.5696 0.5690
## G_Height -9.5101e-03 2.4525e-02 -0.3878 0.6982
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coef(lfit)%&gt;%exp%&gt;%round(5)%&gt;%data.frame%&gt;%pull</code></pre>
<pre><code>## [1] 4.91084 0.99996 0.99053</code></pre>
<pre class="r"><code>iof$prob&lt;-predict(lfit,type=&quot;response&quot;) #get predicted probabilities
iof$predicted&lt;-ifelse(iof$prob&gt;.8,&quot;True&quot;,&quot;False&quot;) #predicted outcome

#confusion matrix
table(prediction=iof$predicted,truth=iof$y)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction FALSE TRUE Sum
##      False    20   63  83
##      True     72  332 404
##      Sum      92  395 487</code></pre>
<pre class="r"><code>(20+332)/487 #accuracy</code></pre>
<pre><code>## [1] 0.7227926</code></pre>
<pre class="r"><code>332/395 #sensitivity </code></pre>
<pre><code>## [1] 0.8405063</code></pre>
<pre class="r"><code>20/92 #specificity</code></pre>
<pre><code>## [1] 0.2173913</code></pre>
<pre class="r"><code>332/404 #recall</code></pre>
<pre><code>## [1] 0.8217822</code></pre>
<pre class="r"><code>iof &lt;- iof %&gt;% mutate(outcome=ifelse(y==&quot;TRUE&quot;,&quot;Treatment&quot;,&quot;Control&quot;))
iof$logit&lt;-predict(lfit) #get predicted log-odds
iof$outcome&lt;-factor(iof$outcome,levels=c(&quot;Treatment&quot;,&quot;Control&quot;))
ggplot(iof,aes(logit, fill=outcome))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
iof &lt;- iof %&gt;% mutate(y1=ifelse(y==&quot;TRUE&quot;,1,0))
ROCplot&lt;-ggplot(iof)+geom_roc(aes(d=y1,m=prob), n.cuts=0)
ROCplot</code></pre>
<p><img src="/jung_project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5210649</code></pre>
<pre class="r"><code>#10 fold CV
class_diag &lt;- function(probs,truth){
#CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
#CALCULATE EXACT AUC
ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
} 

set.seed(1234)
k=10 #choose number of folds
data&lt;-iof[sample(nrow(iof)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(iof)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){
## Create training and test sets
train&lt;-data[folds!=i,]
test&lt;-data[folds==i,]
truth&lt;-test$y1 ## Truth labels for fold i
## Train model on training set (all but fold i)
lfit&lt;-glm(y~D_Area+G_Height,data=train,family=&quot;binomial&quot;)
## Test model on test set (fold i)
probs&lt;-predict(lfit,newdata = test,type=&quot;response&quot;)
## Get diagnostics for fold i
diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##        acc sens spec      ppv       auc
## 1 0.811267    1    0 0.811267 0.4825238</code></pre>
<p>Controlling for Grass Height, every unit increase in Dune Area multiplies odds by a factor of 0.99996. Controlling for Dune Area, every unit increase in Grass Height multiplies odds by a factor of 0.99053. The intercept of 4.91 is the predicted odds of Treatment when D_Area and G_Height is 0.</p>
<p>The probability threshold was moved from 0.5 to 0.8 because at 0.5, all cases were being predicted as Treatment. The accuracy is 0.72, sensitivity is 0.84, specificity is 0.22, and recall is 0.82. The accuracy (proportion of correctly classified cases) is okay but not great. Sensitivity (proportion of Treatment correctly classified) is fairly good. Specificity (proportion of Control correctly classified) is not good. Recall (the proportion classified as Treatment that actually are Treatment) is fairly good.</p>
<p>Low AUC (0.52) indicates that the model is not predicting well and classified as a bad model. ROC curve indicates that the model is giving chance predictions and Sensitivity=Specificity.</p>
<p>After a 10-fold CV, accuracy is 0.81, sensitivity is 1, and recall is 0.81.</p>
<pre class="r"><code>#6. LASSO Regression
library(glmnet)
las &lt;- iof %&gt;% select(Treatment, D_Area, D_Height, G_Area, G_Height, outcome)

y&lt;-as.matrix(las$outcome) #grab response
x&lt;-model.matrix(outcome~.,data=las)[,-1] #grab predictors
head(x)</code></pre>
<pre><code>## TreatmentT2 TreatmentT3 TreatmentT4 TreatmentT5 D_Area
D_Height G_Area G_Height
## 1 0 0 0 0 0.00000 0.0 11.62389 6.8
## 2 0 0 0 0 686.43799 5.0 368.03758 8.0
## 3 0 0 0 0 105.65176 4.6 48.38053 1.4
## 4 0 0 0 0 0.00000 0.0 12.01659 3.0
## 5 0 0 0 0 129.11946 1.5 27.48894 16.0
## 6 0 0 0 0 46.93539 1.6 14.29425 2.5</code></pre>
<pre class="r"><code>x&lt;-scale(x)

cv&lt;-cv.glmnet(x,y,family= &quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 9 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                    s0
## (Intercept)  5.363789
## TreatmentT2  .       
## TreatmentT3 -5.837879
## TreatmentT4  .       
## TreatmentT5  .       
## D_Area       .       
## D_Height     .       
## G_Area       .       
## G_Height     .</code></pre>
<pre class="r"><code>#10 fold CV
las &lt;- iof %&gt;% select(Treatment, D_Area, D_Height, G_Area, G_Height, outcome, y1)
set.seed(1234)
k=10 #choose number of folds
data&lt;-las[sample(nrow(las)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(las)),breaks=k,labels=F) #create folds
diags&lt;-NULL
for(i in 1:k){
## Create training and test sets
train&lt;-data[folds!=i,]
test&lt;-data[folds==i,]
truth&lt;-test$y1 ## Truth labels for fold i
## Train model on training set (all but fold i)
lafit&lt;-glm(y1~Treatment,data=train,family=&quot;binomial&quot;)
## Test model on test set (fold i)
probs&lt;-predict(lafit,newdata = test,type=&quot;response&quot;)
## Get diagnostics for fold i
diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##   acc sens spec ppv auc
## 1   1    1    1   1   1</code></pre>
<p>The LASSO regression showed that the best variable to predict outcome is Treatment 3. The accuracy is 1, which is better than the logistic accuracy of 0.72. It makes sense that Treatment 3 best predicts the outcome (control or treatment) and results in high accuracy because Treatment 3 are the control cases and any other cases that is not Treatment3 is considered to be classified as Treatment.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
